name: Mon first
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
jobs:
  Mon-Premier:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du Repo
        uses: actions/checkout@v3
      - name: Liste le contenu du dossier
        run: ls