name: Mon first
on: [push]
jobs:
  Mon-Premier:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du Repo
        uses: actions/checkout@v3
      - name: Liste le contenu du dossier
        run: ls